services:
  torff-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: torff_container
    ports:
      - "8080:8080" 
    volumes:
      - ./src/Torff.Server/wwwroot:/app/wwwroot
      - ./torff.json:/app/torff.json
    tty: true